### ISSUE TITLE
Clé dauth

### ISSUE THREAD

**Issue by NathanDM** [wuic/wuic#222]
Wuic ne retourne pas la clé dauth de mn appartment

**Comment by corentin59** [comment]
Me too... Same problem... Pour opinion ?

**Comment by corentin59** [comment]
Me too... Same problem... Your opinion ?

**Comment by QLevaslot** [comment]
Have you tried with sancho key?

**Comment by adsanche** [comment]
Can you please provide a quick fix for that issue ? It is not production ready for now.
