### ISSUE TITLE
Inspect JS/CSS file to remove source map 

### ISSUE THREAD

**Issue by gdrouet** [wuic/wuic#46]
When we aggregate/minify scripts, source map is broken so we should remove them

**Comment by gdrouet** [comment]
The statement is actually not rewritten but still exists. It should be totally removed.

**Comment by gdrouet** [comment]
@corentin59 touche pas à mes milestone vilain :-)

**Comment by corentin59** [comment]
J'ai touche un truc ? Je voulais juste voir la description du source map.
Voir comment t'avais gère le truc
Le 27 mai 2015 11:16 PM, "Guillaume DROUET" notifications@github.com a
écrit :

**Comment by gdrouet** [comment]
Pas grave. L'aggrégation casse le sourcemap donc je le retire pour l'instant. Je vais agréger les sourcemaps dans une future release avec un truc comme ça: https://github.com/gdrouet/sourcemap-aggregation-test
